version: '3'


#
#
# Services
#
#
services:

  #
  #
  # Infrastrucure
  #
  #

  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=CyberSecurity
    ports:
      - "9000:8000"
      - "9088:8088"
    volumes:
      - splunk-data:/opt/splunk/var
    networks:
      virtual-net:
        ipv4_address: 172.18.1.3


  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_admin
      MONGO_INITDB_ROOT_PASSWORD: CyberSecurity
    volumes:
      - mongodb_data:/data/db
    networks:
      virtual-net:
        ipv4_address: 172.18.1.4


  nessus:
    image: tenable/nessus
    container_name: nessus
    ports:
      - "8834:8834"
    environment:
      - ACCEPT_EULA=Y
      - NASL_CACHE_SIZE=200
      - NASL_CACHE_EXPIRATION=15m
      - NESSUS_UPDATE=1
      - USERNAME=nessus
      - PASSWORD=CyberSecurity
      - ACTIVATION_CODE=L2BF-A3G7-FP24-CHC9-89NJ
    volumes:
      - nessus_data:/opt/nessus/var/nessus
      - nessus_logs:/opt/nessus/var/nessus/logs
    restart: always
    networks:
      virtual-net:
        ipv4_address: 172.18.1.6


  #
  #
  # Test Environment
  #
  #

  metasploitable2:
    image: tleemcjr/metasploitable2
    ports:
      - "2222:22"   # SSH
      - "9080:80"     # HTTP
      - "9443:443"   # HTTPS
      - "139:139"   # SMB
      - "445:445"   # SMB
    tty: true
    networks:
      virtual-net:
        ipv4_address: 172.18.1.5


#
#
# Networks
#
#
networks:
  virtual-net:
    name: virtual-net
    ipam:
      driver: default
      config:
        - subnet: "172.18.1.0/24"


volumes:
  splunk-data:
  mongodb_data:
  nessus_data:
  nessus_logs: