version: '3'


#
#
# Services
#
#
services:

  #
  #
  # Infrastrucure
  #
  #

  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=CyberSecurity
    ports:
      - "8000:8000"
      - "8088:8088"
    volumes:
      - splunk-data:/opt/splunk/var
    networks:
      virtual-net:
        ipv4_address: 192.168.12.3




  #
  #
  # Test Environment
  #
  #

  metasploitable2:
    image: tleemcjr/metasploitable2
    ports:
      - "2222:22"   # SSH
      - "9080:80"     # HTTP
      - "9443:443"   # HTTPS
      - "139:139"   # SMB
      - "445:445"   # SMB
    tty: true



#
#
# Networks
#
#
networks:
  virtual-net:
    name: virtual-net
    ipam:
      driver: default
      config:
        - subnet: "192.168.12.0/24"


volumes:
  splunk-data: