version: '3'


#
#
# Services
#
#
services:

  #
  #
  # Infrastrucure
  #
  #

  splunk:
    image: splunk/splunk:latest
  	container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=<your_splunk_admin_password>
    ports:
      - "8000:8000"
      - "8088:8088"
    volumes:
       - splunk-data:/opt/splunk/var
    volumes:
      splunk-data:
    networks:
      app-net:
        ipv4_address: 192.168.12.35




  #
  #
  # Test Environment
  #
  #




#
#
# Networks
#
#
networks:
  #
  # Application Network
  #
  app-net:
    name: app-net
    ipam:
      driver: default
      config:
        - subnet: "192.168.12.0/24"
  #
  # Vulnerabilities Network
  #
  vuln-net:
    name: vuln-net
    ipam:
      driver: default
      config:
        - subnet: "192.168.13.0/24"
