version: '3'


#
#
# Services
#
#
services:

  #
  #
  # Infrastrucure
  #
  #

  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=CyberSecurity
    ports:
      - "9000:8000"
      - "9088:8088"
    volumes:
      - splunk-data:/opt/splunk/var
    networks:
      virtual-net:
        ipv4_address: 172.18.1.3


  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_admin
      MONGO_INITDB_ROOT_PASSWORD: CyberSecurity
    volumes:
      - mongodb_data:/data/db
    networks:
      virtual-net:
        ipv4_address: 172.18.1.4



  #
  #
  # Test Environment
  #
  #

  metasploitable2:
    image: tleemcjr/metasploitable2
    ports:
      - "2222:22"   # SSH
      - "9080:80"     # HTTP
      - "9443:443"   # HTTPS
      - "139:139"   # SMB
      - "445:445"   # SMB
    tty: true
    networks:
      virtual-net:
        ipv4_address: 172.18.1.5


#
#
# Networks
#
#
networks:
  virtual-net:
    name: virtual-net
    ipam:
      driver: default
      config:
        - subnet: "172.18.1.0/24"


volumes:
  splunk-data:
  mongodb_data: